### ISSUE TITLE
Getting an issue on trying this plugin on Windows 10

### ISSUE THREAD

**Issue by nishmastercoder** [testdotai/appium-classifier-plugin#17]
Hi Team,
This is a wonderful plugin and can easily visualize it's bright future.
I tried to give it a shot on Windows 10 machine for Android.
I was able to install the plugin successfully using npm install
But, when I try to execute my script having driver.FindElement("-custom","ai:plus");
I receive this error:-
{ Error: Cannot find module '../build/Release/canvas.node'
    at require (internal/modules/cjs/helpers.js:22:18)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15) code: 'MODULE_NOT_FOUND' }

Somewhere I read to upgrade node.js to latest version to get rid of this issue. But, even after upgrading to 10.15.3, getting same error.
Any idea why this might be occurring?
Any near future plans for supporting this plugin against Windows ? It would be awesome if it starts working against Windows.

Thanks & Regards,
Nishant Shah

**Comment by nishmastercoder** [comment]
Hi Team,
Any updates on this?

**Comment by nishmastercoder** [comment]
Hi Team,
Any updates on this ?
